-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS ASIAKAS CASCADE; 
DROP TABLE IF EXISTS TUOTE CASCADE;
DROP TABLE IF EXISTS TILAUS CASCADE; 
DROP TABLE IF EXISTS TOIVEET CASCADE;
DROP TABLE IF EXISTS LIITOSTAULU CASCADE;